name: Release with maven
on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "next release version"
        required: true
      snapshotVersion:
        description: "next snapshot version"
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout specified branch
        uses: actions/checkout@v4

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'

      - name: configure ssh settings
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: configure git settings
        run: |
          git config user.email "cjacobme@aol.com"
          git config user.name "Github Scheduling API"

      - name: build the release
        run: |
          echo "release= "${{ github.event.inputs.releaseVersion }}
          echo "snapshot="${{ github.event.inputs.snapshotVersion }}
          mvn -B -DdevelopmentVersion=${{ github.event.inputs.snapshotVersion }} -DreleaseVersion=${{ github.event.inputs.releaseVersion }} -DtagNameFormat=@{project.version} release:prepare release:perform -s settings.xml
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}