name: Release with maven
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "The branch to checkout when building the release. Later to be limited to main"
        required: true
        default: "main"
      releaseVersion:
        description: "next release version"
        required: true
      snapshotVersion:
        description: "next snapshot version"
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout specified branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.events.branch }}

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'

      - name: configure ssh settings
        run: |
          eval $(ssh-agent -s)
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
          echo ${{ secrets.SSH_KEY }}  | tr -d '\r' | ssh-add -
          git config user.email "cjacobme@aol.com"
          git config user.name "Github Scheduling API"

      - name: checkout branch to be built
        uses: actions/checkout@4
        with:
          ref: ${{ github.events.inputs.branch }}

      - name: build the release
        run: mvn -B -DdevelopmentVersion=${{ github.events.snapshotVersion }} -DreleaseVersion=${{ github.events.releaseVersion }} -DtagNameFormat=@{project.version} release:prepare release:perform -s settings.xml